---
  - name: start consul container
    docker:
      name: swarm-discovery
      image: progrium/consul
      state: reloaded
      ports: 
        - "8500:8500"
      command: "-server -bootstrap"
    when: ansible_hostname == hostvars[groups['swarm_managers'][0]]['ansible_hostname']

  - name: swarm HA primary mgr
    shell: docker run -d -p 3376:3376 -v /var/docker/certs:/var/docker/certs:ro --name swarm-manager swarm manage --discovery-opt kv.tls=true --discovery-opt kv.tlsverify=true --discovery-opt kv.tlscacert=/var/docker/certs/ca.pem --discovery-opt kv.tlscert=/var/docker/certs/servercert.pem --discovery-opt kv.tlskey=/var/docker/certs/serverkey.pem --tlsverify --tlscacert=/var/docker/certs/ca.pem --tlscert=/var/docker/certs/servercert.pem --tlskey=/var/docker/certs/serverkey.pem -H :3376 --replication --advertise {{ansible_fqdn}}:3376 consul://{{ansible_fqdn}}:8500
    when: ansible_hostname == hostvars[groups['swarm_managers'][0]]['ansible_hostname']

  - name: swarm HA secondary mgr
    shell: docker run -d -p 3376:3376 -v /var/docker/certs:/var/docker/certs:ro --name swarm-manager swarm manage --discovery-opt kv.tls=true --discovery-opt kv.tlsverify=true --discovery-opt kv.tlscacert=/var/docker/certs/ca.pem --discovery-opt kv.tlscert=/var/docker/certs/servercert.pem --discovery-opt kv.tlskey=/var/docker/certs/serverkey.pem --tlsverify --tlscacert=/var/docker/certs/ca.pem --tlscert=/var/docker/certs/servercert.pem --tlskey=/var/docker/certs/serverkey.pem -H :3376 --replication --advertise {{ansible_fqdn}}:3376 consul://{{hostvars[groups['swarm_managers'][0]]['ansible_fqdn']}}:8500
    when: ansible_hostname == hostvars[groups['swarm_managers'][1]]['ansible_hostname']