---
- hosts: all
  user: root
  roles:
    - discover
  
- hosts: ca
  user: root
  roles:
    - certs
  vars:
    - cert_email: example@example.com
    - cert_state: NY
    - cert_country: US
    - cert_org: Example Org
    - cert_ou: Example Unit

- hosts: swarm_discovery:swarm_managers:swarm_nodes
  user: root
  roles:
    - docker
  vars:
    - discovery_fqdn: consul://{{hostvars[groups['swarm_discovery'][0]]['ansible_fqdn']}}:8500
    - docker_conf: docker.devicemapper.conf.j2
    #- discovery_fqdn: zk://node1:port,node2:port/optionalpath
    #- docker_conf: docker.conf.j2

- hosts: swarm_discovery
  user: root
  roles:
    - swarm-discovery
  
- hosts: swarm_managers:swarm_nodes
  user: root
  roles:
    - swarm-servers
  vars:
    - discovery_fqdn: consul://{{hostvars[groups['swarm_discovery'][0]]['ansible_fqdn']}}:8500
    #- discovery_fqdn: zk://node1:port,node2:port/optionalpath